### ISSUE TITLE
Decide on implementation of caught-up-ness information needed by Network

### ISSUE THREAD

**Issue by amesgen** [input-output-hk/ouroboros-consensus#101]
There are two general ways to implement the functionality described in #91:

 - Implement a minimal version of the interface, likely based on some recency condition of the immutable/volatile tip.
 - Decide that the functionality nicely fits into the Genesis State Machine, and we should implement the full/non-trivial parts of the GSM already today.

For context, the Genesis State Machine (GSM) is a part of the current Genesis design that determines when to "disable" certain properties/functionalities of the Consensus layer, as part of "switching" from Genesis to Praos. However, it does not depend on other Genesis components and could be implemented today.

The goal of this ticket is to decide on the implementation route we want to take.

---

Some notes from the 1:1 with @nfrisby today:

 - In general, it seems feasible to use the GSM for that purpose; the core question is, in both cases: "Can we safely resume operation in Praos mode, or do we have to switch to a (in some way more expensive) Syncing mode?"
    - In particular, the transition rule "All peers claim no more headers" for "Syncing -> CaughtUp" also works without Genesis, as we can/have to assume that we are only connected to trusted peers (probably just one) during Syncing.
    - We should avoid transient intermediary states, such as entering the CaughtUp state on startup just to immediately leave it due to our tip being too old.
 - The current interface in https://github.com/input-output-hk/ouroboros-network/pull/4555 does not allow Consensus to "notify" the Networking layer that it should switch back to Syncing after we were caught up, as Network decides when to call the function, implemented by Consensus, that returns the ledger peers to use.
   
   But that might actually be fine, if the transition "CaughtUp -> Syncing" always involves losing all of our peers (in which case Network has to call the function). That should e.g. true when "closing the laptop lid", but also when falling behind due to CPU starvation, as our peers will disconnect from us when the fork gets too deep. We should check this in more detail.

**Comment by nfrisby** [comment]
@amesgen and I discussed this during our call today. Here's the whole argument.

To be explicit: we're proposing implementing this simplified GSM, using Option 2 and Option B below.

-----

The broad question:

- Until Genesis is released, someone (eg the CF, IOG relays, etc) will run a (mostly-)centralized pool of trusted nodes.

- After Issue 91, the node will, at least on start-up and effectively continuously decide whether _all_ of the current upstream peers must be from that trusted pool. If _not_, the upstream peers can include untrusted nodes.

- In fact, when the node can use untrusted nodes, it should _only_ use untrusted nodes, in order to relieve load from the centralized trusted pool. Therefore, the node should switch to untrusted peers ASAP, and it should switch back to trusted peers only when absolutely necessary.

    - In particular, PNSol suggested a network outage of 20min or less should _not_ cause a node to reconnect to the trusted pool.

- This is a simplified version of the Genesis State Machine. In this simplification, the two states are OnlyTrusted and CaughtUp.
     
    - What are the two transitions?

        - CaughtUp -> OnlyTrusted (cf "CaughtUp -> PreSyncing")

            - Option 1: valency drops to 0 (or 1 for a BP's relay)

                - this suffers from false alarms (eg router completely dies for 10 minutes)

            - Option 2: the node's volatile tip is more than X old

                - TODO choose X according to survivable Praos eclipse duration analysis

                - TODO X in units of slots or seconds?

        - OnlyTrusted -> CaughtUp (cf "PreSyncing -> CaughtUp")

            - Option A: the immutable tip is less than Y min old

                - PRO: a little less load on the trusted peers

                - CON: a non-negligible design cost of choosing/maintaining Y

                - CON: different than the corresponding transition in the proper GSM

            - Option B: no peers claim to have subsequent headers

                - (Recall that empty disjunctions are vacuously false.)

                - Perhaps surprsingly, this is viable even without the LoP. Unlike Genesis's Syncing state, _all_ peers are trusted in the OnlyTrusted state.

    - What should the node do at start-up?

        - Whenever the node transitions to OnlyTrusted or CaughtUp, record that transition in the persistent "last transition" file.

        - Upon start-up, read the "last transition" file.

        - If the node was most recently in CaughtUp and its volatile tip is less than X old, enter CaughtUp; otherwise, enter OnlyTrusted.

    - Remark. For the proper GSM, Option 2 and Option B are exactly the same as the proposal, and the start-up behavior is morally the same as well.

**Comment by amesgen** [comment]
The concrete API interface with Network (which is blocking https://github.com/input-output-hk/ouroboros-network/pull/4555) will be resolved by working out an IER (Information Exchange Requirement).
