### ISSUE TITLE
document era numbers for local tx submission protocol

### ISSUE THREAD

**Issue by ashisherc** [input-output-hk/ouroboros-consensus#135]
Many projects now use their custom implementation of local tx submission mini protocol to submit transactions. It is required for us to know the latest spec for the same,

This issue is specific to documenting the era numbers used for submitting the tx, which is to be added in the CDDL as documented in the networking repo. I am assuming it should be the same as the ledger version, but I have had difficulty confirming the same as it is not working as expected, so it is best to mention/document it.

```
          |
          v
eg. [eraNumber, 24(tx)]
```

here are the issue links for other documentation requested,
https://github.com/input-output-hk/ouroboros-network/issues/4521
https://github.com/input-output-hk/cardano-node/issues/5139

**Comment by dnadales** [comment]
Thank you for submitting the issue. I think this should be solved by https://github.com/input-output-hk/ouroboros-network/issues/4581 Feel free to reopen if you think that's incorrect.

**Comment by dnadales** [comment]
Thank you for submitting the issue. I think this should be solved by https://github.com/input-output-hk/ouroboros-network/issues/4581 Feel free to reopen if you think that's incorrect.

**Comment by ashisherc** [comment]
@dnadales I think it will be solved by the referenced issue in detail but would like to know the era values for transaction submission right now for something I am working on.

**Comment by amesgen** [comment]
The era numbers is the 0-based index in the list of all eras, so they are independent of the ledger protocol versions. As of today, we support the following eras (the code base also has some support for Conway already, but that is still experimental):

| Era number | Era       |
|------------|-----------|
| 0          | Byron     |
| 1          | Shelley   |
| 2          | Allegra   |
| 3          | Mary      |
| 4          | Alonzo    |
| 5          | Babbage   |

You also might find [this table](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0059/feature-table.md) (concretely, the "Era" column) helpful.

Hope this helps!

**Comment by ashisherc** [comment]
@amesgen I am aware of the table you shared, but as you have posted, it does not match the ledger version and hence I wanted to make sure of the values used for tx submission. This clarifies, thanks!
