### ISSUE TITLE
cabal build ouroboros causes ghc to panic

### ISSUE THREAD

**Issue by waalge** [input-output-hk/ouroboros-consensus#164]
*External*   otherwise.

**Summary**
ghc panics 
**Steps to reproduce**
```
nix develop
cabal build ouroboros 
```
**Expected behavior**

**System info (please complete the following information):**
NixOS 23.11 (Tapir)

**Screenshots and attachments**
```sample
Building library for ouroboros-consensus-0.7.0.0..
ghc: panic! (the 'impossible' happened)
  (GHC version 9.2.8:
	ModOrigin: hidden module redefined
  x: unusable module
  y: unusable module
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Unit/State.hs:238:14 in ghc:GHC.Unit.State
```

**Additional context**

Given that there is no previous mention of this issue I'm guessing ive done something odd.

**Comment by amesgen** [comment]
I have seen this one before; I am not sure what is causing it. Luckily, it always goes away for me after I run `cabal clean`.

**Comment by waalge** [comment]
thanks - I will try that.
My machine has just reported its completely full... possibly related.

**Comment by waalge** [comment]
I've tried `nix store delete` on paths I can see are somehow connected to the repo. Hoping this would inspire nix to rebuild the env and deps from scratch. That's not helped.

This issue is surely not to do with this repo, but if anyone has suggestions on how to resolve it...

**Comment by dnadales** [comment]
This does not seem like I consensus bug, although I understand it's annoying. Would it make sense to move this to our [discussions](https://github.com/input-output-hk/ouroboros-consensus/discussions) section?

**Comment by waalge** [comment]
I think you can close this.

I hoped if I left it open for a little bit someone in the know might spot this and make a suggestion

**Comment by dnadales** [comment]
They can still make suggestions after the issue is closed ;) Feel free to open a question in the discussion section and thank you!

**Comment by waalge** [comment]
What @amesgen says is, in spirit, right.
While `cabal clean` didn't work, manually deleting `~/.cabal` unblocked the problem. 
Next time that'll be the first thing i try :facepalm:

**Comment by dnadales** [comment]
Glad to know that it worked. It's a pity that the user has to resort to deleting the whole `~/.cabal` directory though :(

**Comment by waalge** [comment]
Hmmm. This happened again. 
And this time I wasnt close to any storage limits, so maybe it wasnt related.

**Comment by dnadales** [comment]
Just FTR, IOG devx team is tracking these kinds of issues.

**Comment by waalge** [comment]
I was unable to repeat the fix. clearing cabal caches alone doesnt seem to be enough

**Comment by amesgen** [comment]
This has been fixed in GHC master by the IOG GHC team; still needs to be backported and then land in a GHC release: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11604

**Comment by amesgen** [comment]
FYI: GHC 9.6.4 was released, which contains [this GHC commit](https://gitlab.haskell.org/ghc/ghc/-/commit/1ae57288cabdd818180f38c9f55d8da8ac4c1d0c), which is a backport of the fix mentioned just above.
