### ISSUE TITLE
Document and propose improvements to the N2C query versioning procedure

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-consensus#190]
We do N2C query versioning mainly for:

- Documentation: we are able to know when a query was added or when we can expect it to be available.
- Better error messages: without versioning we would not know if an error is caused by a bug or by an unsupported query.

# Problem
At the moment, adding a new query requires modifying version information in several places. The process is perhaps more convoluted than it ought to be, and not properly documented which makes it error-prone. 
This makes adding and maintaining queries hard.

For instance, assume we are adding an experimental query, say `Qe` which is enabled by version `7`, which is now the highest. If we later decide to add a new query `Qs` that is stable and want to make available to the node clients, we cannot simply enable it by assigning it to the next available version, `8` in this case, since this would imply that the experimental query `Qe` would be considered stable. What we currently have to do in this case is move `Qe` to version `8` and assign `Qs` to version `7`.

# Goals

We want to simplify the process of adding and maintaining queries. To this end, we elaborated the following goals:

- [x] #267
- [ ] Using the insight gained during the documentation phase try to propose improvements to the query versioning procedure. Think of refactoring and adding new tests. An example could be tests that signal versions as either experimental or stable.

# Related issues

- input-output-hk/ouroboros-network#2685
- input-output-hk/ouroboros-network#3875
- input-output-hk/ouroboros-consensus#167

**Comment by amesgen** [comment]
FTR: There now is documentation for the current query versioning process: https://input-output-hk.github.io/ouroboros-consensus/docs/for-developers/QueryVersioning

**Comment by dnadales** [comment]
We could not identify substantial improvements or new kinds of tests. [This](https://github.com/input-output-hk/ouroboros-consensus/issues/167) issue might be a good next step, but there seems to be no need to keep this issue open after https://github.com/input-output-hk/ouroboros-consensus/pull/273 was merged.
