### ISSUE TITLE
Estimate the number of file descriptors Consensus needs

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-consensus#20]
We need to estimate the number of file descriptors the consensus layer uses, which might be a function of the number of connected clients.

These estimations should be validated empirically.

The node can use this information to check that enough file descriptors are available (see https://github.com/input-output-hk/cardano-node/issues/305): the operator proposes the maximum number of files descriptors that she wants to support, and the node will check if this is enough given the different system parameters such as the number of peers the node should connect to.

**Comment by nfrisby** [comment]
I think there are three elements to this task:

1) Review the design documentation to refresh our expectations about where file handles might be.

2) Look through the code to confirm/refine those expectations into our estimated integer intervals. I _think_ it's conservative to start by finding which pieces of state (eg loop accumulators, reference cells, etc) ultimately contain a `HasFS.Handle` type.

3) As Damian wrote in the description, empirically validate the intervals by running a node with varying numbers of upstream- and downstream-peers.

I suspect the form of our final answer will be:

- Somewhere between `[bLo,bHi]` handles are necessary for the Consensus and Storage layer to run at all.
- Somewhere between `[uLo,uHi]` additional handles will be necessary per upstream-peer.
- Somewhere between `[dLo,dHi]` additional handles will be necessary per downstream-peer.

And so the interval `[bLo+uN*uLo+dN*dLo, bHi+uN*uHi+dN*dHi]` would be a conservative estimate of how many file handles a node with aat most `uN` simultaneous upstream peers and `dN` simultaneous downstream peers might require at a time.

(Maybe we'd need to split upstream into hot upstream, warm upstream, cold upstream etc?)

-----

If that upper bound is too conservative, then we'd likely need to do some of the following:

1) Do some hopefully simple patches that eliminate some wasteful use of file handles.
2) Start reasoning about dependencies of those intervals and/or changes over time (eg maybe we use extra file handles during Storage Layer initialization, but stop using those by the time we'd have network peers?)

**Comment by nfrisby** [comment]
Hmm. Our initialization check will check that the node _process_ is allowed enough file handles.

If we were to hypothetically run two nodes on the same machine, would we ever realistically need to check that the system limit is below 2*the process limit? (Two nodes would be weird, but the comm one node and one wallet would prompt the same basic question.)

[For reasons I don't understand, I am unable to ping Duncan and Sam using GitHub @ syntax in this message. :shrug: I'll send them the link on Slack.]

**Comment by dcoutts** [comment]
I think typical system limits are much higher. I'm not sure it's really the responsibility of the node to check on system wide properties like whether one could plausibly run multiple copies of the node within system wide limits.

The node should remain within its own limits, that's all.

**Comment by bartfrenk** [comment]
# Total
Total number of file descriptors:

49 (base) + #upstream-peers * 2 + #downstream-peers * 1

## Base (49)
### Miscellaneous (14)
- pseudo-terminals (3)
- timerfd (1)
- eventfd and eventpoll (4) 
- pipes (6)
### Shared libraries and the executable itself (22)
### The TCP server (2)
- IPv4
- IPv6
### Chain DB (5)
#### Global (1)
The global lock file
#### Immutable DB (3)
- The chunk file of the active chunk
- The primary index of the active chunk
- The secondary index of the active chunk
#### Volatile DB (1)
- The current write handle for the volatile DB
#### Ledger DB (1)
- Reading the ledger DB snapshot on initialization
## Downstream peers (2)
- The iterator in the immutable DB, if the downstream peer is following the immutable DB
- TCP connection to the downstream peer

## Upstream peers (1)
- The TCP connection to the upstream peer

## Cardano CLI [ping] (1)
- The TCP connection to the client

**Comment by dnadales** [comment]
CC: @disassembler @Jimbo4350 ☝
