### ISSUE TITLE
Bring query utxo by address command performance on par with current version

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-consensus#205]
QA reported that the `query utxo --address` command took about 10 seconds. The baseline (`1.35.0` at the time of testing) took ~2.3 seconds. Furthermore, the query returned an empty set of addresses where 4 addresses were expected.

We need to fix the command and bring the performance of said command on par with the baseline.

This query is inefficient in LMDB because 

- we need to do disk access AND 
- we do it incrementally AND 
- we need to stow the ledger tables.

This query is inefficient in InMemory because

- we do it incrementally AND 
- we need to stow the ledger tables.

Possible solutions:

- `InMemory` can do the query all at once, no need to do it incrementally (8s > 5s).
- Make the UTxO filtering functions target the `CardanoLedgerTables` and then stow the result (should take us to the theoretical limit).
- Make this query faster, for instance by indexing by addresses. 
- Create a service to answer this query.

**Comment by jasagredo** [comment]
Currently this is to be tested via the `cardano-node` executable produced by input-output-hk/cardano-node#5458

It needs:
- input-output-hk/ouroboros-network#4670
- input-output-hk/ouroboros-consensus#337
- input-output-hk/cardano-api#229

**Comment by jasagredo** [comment]
Closing as complete!
