### ISSUE TITLE
Fix UTxO-HD issues found during B&T 

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-consensus#314]
This issue aims to summarize and track the errors reported from the UTxO-HD benchmarking and testing phase.

------------------------------

### Removing an empty list of transactions :white_check_mark: 

In main, the node doesn't crash when the opcert is updated twice. However in the UTxO-HD branch it does. This is fixed by #305 

------------------------------

### Tx-generator blocked on MVar :white_check_mark: 

A silencing handler had been removed and the tx-generator was crashing. This is fixed in input-output-hk/cardano-node@605d1f0b5ffca649e7bd981715845ee5b34a8e85

------------------------------

### ValueNotConserved :white_check_mark: 

Numerous warnings like this one arise in testing.

```
[iog2:cardano.node.Mempool:Warning:127] [2023-08-25 12:51:44.52 UTC] fromList [("err",Object (fromList [("badInputs",Array [String "8bccd59876c7f2ae2f0841fd5ac3eaefd126419d0632c5372e59c38cbf764418#TxIx 0"]),("consumed",Object (fromList [("lovelace",Number 0.0),("policies",Object (fromList []))])),("error",String "This transaction consumed MaryValue 0 (MultiAsset (fromList [])) but produced MaryValue 1000000000 (MultiAsset (fromList []))"),("kind",String "ValueNotConservedUTxO"),("produced",Object (fromList [("lovelace",Number 1.0e9),("policies",Object (fromList []))]))])),("kind",String "TraceMempoolRejectedTx"),("mempoolSize",Object (fromList [("bytes",Number 235.0),("numTxs",Number 1.0)])),("tx",Object (fromList [("txid",String "cf65f585")]))]
```

Running the cluster and throwing these commands at it probably shows the error:
```
cardano-cli transaction build-raw --fee 200927 --out-file 230825_125132902_iive_funding_tx.body --tx-in "8bccd59876c7f2ae2f0841fd5ac3eaefd126419d0632c5372e59c38cbf764418#2" --tx-out "2657WMsDfac6DsG24UTj7pbjGWMVv93osKZJKVWTbpfQM6BE33xs6jYc27W15RDJZ+1000000000" --tx-out "2657WMsDfac58Tc6VykftdDHaMFC6kc4GE1sJU8Vv6rQnduHNr2YXfcWH2h89uaFE+1000000000" --tx-out "addr_test1vqrm7mj9ahtqsne6gtluc32jjvdhzc8nsmd9n6q9ln4f74svgmxjz+99987998803153" --babbage-era

cardano-cli transaction sign --tx-body-file 230825_125132902_iive_funding_tx.body --testnet-magic 42 --signing-key-file /home/martink/Source/repos/cardano-node/state-cluster0/addrs_data/user1_ci0.skey --out-file 230825_125132902_iive_funding_tx.signed

cardano-cli transaction submit --testnet-magic 42 --tx-file 230825_125132902_iive_funding_tx.signed --cardano-mode
```

This command on `cardano-node-tests` should also trigger it:
```
NODE_REV='utxo-hd-8.2.1' DB_BACKEND=lmdb CARDANO_CLI_REV="cardano-cli-8.5.0.0-nix" PYTEST_ARGS="-k 'test_build_transfer_funds[src_shelley-dst_shelley]'" CI_FAST_CLUSTER=1 ./.github/regression.sh
```

*Solution*: it turns out it is just a matter of the trace being upgraded from `Info` to `Warning`, although perhaps this has to be reverted. See input-output-hk/cardano-node@87638777e42a288747b4064a673502b1cd408837

------------------------------

### Excessive tracing :white_check_mark: 

The BackingStore traces are interfering with the eliding tracers and producing millions of lines more of logging. We have decided to move these to a separate tracer that is silent by default. See input-output-hk/cardano-node#5449

------------------------------

### Mempool regression :white_check_mark: 

A regression was observed in the mempool. Snapshotting times were too high. This was solved by #347

**Comment by dnadales** [comment]
All issues detected during benchmarking and testing were addressed.
