### ISSUE TITLE
[BUG] - Flooded with github notifications

### ISSUE THREAD

**Issue by facundominguez** [input-output-hk/ouroboros-consensus#399]
**Internal/External**
*Internal*

**Summary**
I get notifications for every PR and comment in the repo because the `ouroboros-consensus` team is a code owner of the whole repo. The amount of notifications makes it tedious to filter them all.

**Expected behavior**
Ideally, I would only get notifications for issues that mention me explicitly, which probably would require removing `ouroboros-consensus` from the code owners.

**Comment by nfrisby** [comment]
Thanks. I agree.

I have so far handled this via gmail filters. EG

```
Matches: list:(github.com) -{nfrisby list:(ouroboros-consensus.input-output-hk.github.com)}
Do this: Skip Inbox, Apply label "Other git repos"
```

**Comment by dnadales** [comment]
I removed you and your other Tweag colleagues from the Consensus GH team and added you as individual contributors. Let me know if the problem persists.

**Comment by dnadales** [comment]
... and sorry  about the spam :pray:

**Comment by facundominguez** [comment]
Thanks @dnadales!

> I have so far handled this via gmail filters. EG

Thanks @nfrisby. I fiddled with gmail filters for a bit but couldn't find something too satisfactory.
