### ISSUE TITLE
Rename translateLedgerView to crossEraForecast

### ISSUE THREAD

**Issue by nfrisby** [input-output-hk/ouroboros-consensus#80]
I've been confused multiple times by this name. This function _does not_ translate a ledger view from one era to the next.

```
data EraTranslation xs = EraTranslation {
      ...
    , translateLedgerView    :: InPairs (RequiringBoth WrapLedgerConfig    (TranslateForecast LedgerState WrapLedgerView)) xs
    }
```

It would probably make sense to rename `EraTranslation` (since it does not just contain translations) and `TranslateForecast` as well.

**Comment by amesgen** [comment]
I think the concrete things to rename would be:

 - Rename `translateLedgerView` to `crossEraForecast`, as it is too easy to interpret that name to mean "translate a `LedgerView` from one era to another".
 - Rename `TranslateLedgerView` to sth like `CrossEraForecast` (that exact name might be somewhat misleading, as it is not directly a cross-era analogue of `Forecast`) or `CrossEraForecaster`; as well as the selector in a similar way.
 - Rename `EraTranslation` to sth like `CrossEraLogic` if we think that the term "translation" should only be used when a cross-era conversion involves the *same kind of thing* (ledger state, ledger view, chain-dep state, ...) in both eras.

Also, the Haddock for `TranslateLedgerView` should be fixed:

https://github.com/input-output-hk/ouroboros-consensus/blob/12cec3b3aa4938c1910909832fe0b2db592775c0/ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/State/Types.hs#L79-L88

The first two paragraphs should rather read like e.g.
```haskell
-- | Translate @f x@ to a @'Ticked' (g y)@ across an era transition.
--
-- Typically @f@ will be instantiated with 'LedgerState' and @g@ with
-- 'WrapLedgerView'.
```
