### ISSUE TITLE
Expose batch size for table traversing queries as a configuration parameter

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/ouroboros-consensus#97]
The `TranversingQueryHandler` will perform range reads of currently `100_000` at a time. This value should be configurable. See `handleTraversingQuery` in `O.C.L.Query`

**Comment by jorisdral** [comment]
Blocked on #43 and https://github.com/input-output-hk/ouroboros-network/issues/4543

**Comment by jorisdral** [comment]
I think we can close this one, since we have `onDiskShouldFlush` in the `DiskPolicy`
